# Generated by Django 4.2.7 on 2023-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('venue', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
